curl https://my-kube-playground:6443/api/v1/pods --key admin.key --cert admin.crt --cacert ca.crt

kubectl config view
kubectl config current-context

kubectl create ns dev
kubectl config set-context --current --namespace=dev
kubectl config view

cat .kube/config
