
# Create a RuntimeClass in kubernetes
apiVersion: node.k8s.io/v1  
kind: RuntimeClass
metadata:
  name: gvisor  
handler: runsc


---
# create a pod which uses runsc runtime from gvisor
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  runtimeClassName: gvisor
  containers:
  - image: nginx
    name: nginx
