# On Node01 go to dir /var/lib/kubelet
# create directory seccomp and profiles here
# Put below violation.json in /var/lib/kubelet/seccomp/profiles/violation.json
{
  "defaultAction": "SCMP_ACT_ERRNO"
}

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: test-violation
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/violation.json
  containers:
  - name: ubuntu1
    image: ubuntu
    command: ["bash", "-c", "echo 'Syscalls invoked' && sleep 100"]
EOF

# verify pod failed to start by kubectl describe pod test-violation

Now replace the seccomp profile type to RuntimeDefault and create the pod again to verify it runs successfully



